# Generated by Django 2.1.7 on 2019-04-16 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='msg_send_from_me', to='Software.User')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='msg_send_to_me', to='Software.User')),
            ],
        ),
        migrations.CreateModel(
            name='RecentContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_view_time', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_recent_contacts', to='Software.User')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Software.User')),
            ],
        ),
    ]
