# Generated by Django 2.1.7 on 2019-04-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0002_auto_20190428_2346'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recentcontacts',
            unique_together={('user1', 'user2')},
        ),
    ]
