# Generated by Django 2.1.7 on 2019-05-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0002_auto_20190428_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_project', to='Software.User', verbose_name='项目创建者'),
        ),
        migrations.AlterField(
            model_name='project',
            name='security_level',
            field=models.IntegerField(choices=[(0, '低 - 任何人可见'), (1, '中 - 所有投资人可见'), (2, '高 - 大投资人可见')], default=0, verbose_name='项目保密等级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='bBFRnNqZ', max_length=10),
        ),
    ]
