# Generated by Django 2.1.7 on 2019-05-12 02:09

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0003_auto_20190511_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='uploaded/noface.gif', upload_to='uploaded'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='CjTDrS70', max_length=10),
        ),
    ]
