# Generated by Django 2.1.7 on 2019-05-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0005_auto_20190513_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='Ytp16rR8', max_length=10),
        ),
    ]
