# Generated by Django 2.1.7 on 2019-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0007_auto_20190515_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(default='尚待补充', max_length=1000, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='ing94D6t', max_length=10),
        ),
    ]
