# Generated by Django 2.1.7 on 2019-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0008_auto_20190515_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='申请人id')),
                ('company', models.CharField(max_length=100, verbose_name='所属公司')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('scale', models.CharField(max_length=100, verbose_name='投资规模')),
                ('currency', models.CharField(max_length=100, verbose_name='投资币种')),
                ('introduction', models.TextField(max_length=10000, verbose_name='简介')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='V1jX2KI7', max_length=10),
        ),
    ]
