# Generated by Django 2.1.7 on 2019-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0010_auto_20190516_0442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='DjgNslk6', max_length=10),
        ),
    ]
