# Generated by Django 2.1.7 on 2019-05-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0011_auto_20190517_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='所属公司')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('scale', models.CharField(max_length=100, verbose_name='投资规模')),
                ('currency', models.CharField(max_length=100, verbose_name='投资币种')),
                ('introduction', models.TextField(max_length=10000, verbose_name='简介')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='CLxdX0RK', max_length=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='Software.User', verbose_name='申请用户'),
        ),
    ]
