# Generated by Django 2.1.7 on 2019-05-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0012_auto_20190517_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmstring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Software.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='jbHA23Rx', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='confirmstring',
            unique_together={('user', 'type')},
        ),
    ]
